import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="relativist">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img className="bg-image bg-big" src="/wall.jpg" alt="background" />
      <img className="bg-small" src="/wall_mob2.jpg" alt="background" />
      <div className="stripe"></div>
      <div className="home-gridder">
        <ul className="centerBreathing">
          <li className="li-cc breathing">
            <Link href="/cine-concerts">
              <a>Ciné-concerts</a>
            </Link>
          </li>
          <li className="li-c breathing">
            <Link href="/concerts">
              <a>Concerts</a>
            </Link>
          </li>

          <li className="li-t breathing">
            <Link href="/theatre">
              <a>Théâtre</a>
            </Link>
          </li>
          <li className="li-m breathing">
            <Link href="/cinema">
              <a>Cinéma</a>
            </Link>
          </li>
        </ul>

        <div className="hero">
          <div className="hero-slug">
            Pianiste, compositeur, musicien de scène
          </div>
          <div className="hero-title">Vadim Sher</div>
        </div>
      </div>
    </div>
  );
};

export default Home;
